### ISSUE TITLE
[BUG] Keyboard inputs

### ISSUE THREAD

**Issue by Goniix** [Goniix/Nungeon#9]
### Describe the bug
Keyboard inputs are needed for player movement methods

### Expected behavior
Keyboard inputs in form (x,y) (x being 0 if idle, -1 if left, +1 if right and y being, 0 if idle -1 if up, +1 if down)

**Comment by pioupia** [comment]
https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by pioupia** [comment]
https://github.com/boppreh/keyboard

**Comment by pioupia** [comment]
Passage sous PyGame. Problème résolu. #21
